version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: Rhfcyfz180
      POSTGRES_DB: CarCompany1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
